### PR TITLE
fix: Clusterwide quota calculation

### LINKED ISSUE #568: bug: Clusterwide quota calculation incorrect
# Bug Report

**Paas Operator version:**

v1.13.1 

**Current behaviour:**

The size of the clusterwide resource quote has been dramatically reduced when migrating from v1.12.0 to v1.13.0. It is not understandable how the calculation has been made and why the change in size is desired from the operators perspective.

**Expected behaviour:**

The size of the clusterwide resource quota is unchanged when migrating from v1.12.0 to v1.13.0

**Steps to reproduce:**

Deploy v1.13.0
Configure a capability with a clusterwide_quota = true
Add multiple Paas'es which request the capability 
Do not see a change in the size of the clusterwide_quota

**Related code:**

```
insert short code snippets here
```

**Other information:**

### PR DESCRIPTION
**Pull request by portly-halicore-76**
## Pull Request type

Please check the type of change your PR introduces:

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## What is the current behavior?

Clusterwide quota calcaluted incorrect, due to variable shadowing. 

Fixes: #568

## What is the new behavior?

Clusterwide quota calculated correctly.

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: internal/controller/cluster_wide_quota.go [hunk 1]
```diff
@@ -69,18 +69,25 @@ func (r *PaasReconciler) updateClusterWideQuotaResources(
...
+	allPaasResources, err = r.fetchAllPaasCapabilityResources(ctx,
 		quota,
-		configCapability.QuotaSettings.DefQuota,
-	); err != nil {
+		c.QuotaSettings.DefQuota,
+	)
+	if err != nil {
 		return err
 	}
+	configCapability = c
```
Comment (AxiomaticFixedChimpanzee) [inline internal/controller/cluster_wide_quota.go]: I think we can just replaces all references of `configCapability` with `c`, and remove the `configCapability` declaration altogether.

**Review by AxiomaticFixedChimpanzee — DISMISSED** [review]

**Review by AxiomaticFixedChimpanzee — APPROVED** [review]
